#!/bin/bash

cd /home/mattmc/projects/tpp/server

export DISPLAY=:0.0

sudo killall server_ssl > /dev/null
sleep 1

sudo killall firefox > /dev/null
sleep 3

node server_ssl.js &

#chromium-browser --app=https://localhost:8443/robot.html > /dev/null &
firefox https://localhost:8443/robot.html > /dev/null &

