#!/bin/bash

cd /home/mattmc/projects/tpp/server

export DISPLAY=:0.0

sudo killall node-easyrtc > /dev/null

sleep 1

sudo killall chromium-browser > /dev/null

sleep 3

node server_ssl.js &

chromium-browser --kiosk --app=https://localhost:8443/robot.html > /dev/null &

